{{- if .Values.fin.ingress.enabled -}}
{{- $fullName := include "hopps.finFullname" . -}}
{{- $ingressPath := .Values.fin.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hopps.finLabels" . | nindent 4 }}
{{- with .Values.fin.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if or (.Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass") (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/IngressClass") }}
  {{- if .Values.fin.ingress.ingressClassName }}
  ingressClassName: {{ .Values.fin.ingress.ingressClassName }}
  {{- end }}
  {{- end }}
{{- if .Values.fin.ingress.tls }}
  tls:
  {{- range .Values.fin.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.fin.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - pathType: Prefix
            path: {{ $ingressPath }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
  {{- end }}
{{- end }}