{{- if .Values.fin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fin.serviceAccount.name | default (include "hopps.finFullname" .) }}
  labels:
    {{- include "hopps.finLabels" . | nindent 4 }}
  {{- with .Values.fin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.fin.serviceAccount.automount }}
{{- end }}
