apiVersion: v1
kind: Service
metadata:
  name: {{ include "hopps.finFullname" . }}
  labels:
    {{- include "hopps.finLabels" . | nindent 4 }}
spec:
  type: {{ .Values.fin.service.type }}
  ports:
    - port: {{ .Values.fin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "hopps.finSelectorLabels" . | nindent 4 }}
