apiVersion: v1
kind: Service
metadata:
  name: {{ include "hopps.frontendFullname" . }}
  labels:
    {{- include "hopps.frontendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hopps.frontendSelectorLabels" . | nindent 4 }}
