apiVersion: v1
kind: Service
metadata:
  name: {{ include "hopps.azDocumentAiFullname" . }}
  labels:
    {{- include "hopps.azDocumentAiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.azDocumentAi.service.type }}
  ports:
    - port: {{ .Values.azDocumentAi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hopps.azDocumentAiSelectorLabels" . | nindent 4 }}
