{{- if .Values.azDocumentAi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.azDocumentAi.serviceAccount.name | default (include "hopps.azDocumentAiFullname" .) }}
  labels:
    {{- include "hopps.azDocumentAiLabels" . | nindent 4 }}
  {{- with .Values.azDocumentAi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.azDocumentAi.serviceAccount.automount }}
{{- end }}
