apiVersion: v1
kind: Service
metadata:
  name: {{ include "hopps.orgFullname" . }}-management
  labels:
    {{- include "hopps.orgLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "hopps.orgSelectorLabels" . | nindent 4 }}
