{{- if .Values.org.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.org.serviceAccount.name | default (include "hopps.orgFullname" .) }}
  labels:
    {{- include "hopps.orgLabels" . | nindent 4 }}
  {{- with .Values.org.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.org.serviceAccount.automount }}
{{- end }}
