name: Build project and run sonarqube analysis

on:
  push:
    paths:
      - backend/**
      - .github/workflows/backend-sonarqube-analysis.yml
    branches: [ 'main' ]
  pull_request:
    paths:
      - backend/**
      - .github/workflows/backend-sonarqube-analysis.yml
    types: [opened, reopened, synchronize]


jobs:
  build-and-analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: mvn package
        run: mvn -B package --file backend/pom.xml

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            --file backend/pom.xml \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=hopps-app \
            -Dsonar.projectKey=hopps-app_hopps
