name: CI/CD Pipeline for frontend

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend/spa

      - name: Run tests
        run: pnpm run validate
        working-directory: frontend/spa

      - name: Build project
        run: pnpm run build && ls -la
        working-directory: frontend/spa

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: frontend/spa/dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker image tag
        id: get-version
        run: |
          if git describe --tags --exact-match 2>/dev/null; then
            VERSION=$(git describe --tags --exact-match)
            echo "VERSION=${VERSION#spa-}" >> $GITHUB_ENV
            echo "TAG=hopps/spa:${VERSION#spa-}" >> $GITHUB_ENV
          else
            echo "TAG=hopps/spa:${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          fi

#      - name: Set build number
#        run: echo "BUILD_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: frontend/spa
          file: frontend/spa/docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:${{ env.VERSION }}